name: 'Trivy CVE GitHub issue'
description: ''
inputs:
  github-token:
    description: 'GitHub token'
    required: true
  trivy-version:
    description: 'Trivy version'
    default: '0.34.0'
    required: false
  debug:
    description: 'Debug'
    default: 'false'
    required: false
  files:
    description: 'Files'
    default: '**/*.yaml'
    required: false
  severity:
    description: 'Severity'
    default: 'CRITICAL,HIGH'
    required: false
  issue-rate-limit:
    description: 'Issue rate limit'
    default: '10'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Prepare trivy
      run: |
        cd /tmp
        curl -fsSL https://github.com/aquasecurity/trivy/releases/download/v${VERSION}/trivy_${VERSION}_Linux-64bit.tar.gz | tar xz
        mv trivy /usr/local/bin
        trivy --version
      env:
        VERSION: ${{ inputs.trivy-version }}
      shell: bash
    - name: Update CVE database
      run: |
        trivy image --download-db-only
      shell: bash
    - name: Run
      run: |
        node ${{ github.action_path }}/dist/index.js
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        DEBUG: ${{ inputs.debug }}
        FILES: ${{ inputs.files }}
        SEVERITY: ${{ inputs.severity }}
        ISSUE_RATE_LIMIT: ${{ inputs.issue-rate-limit }}
      shell: bash